In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### Data Collection

In [2]:
df=pd.read_csv("../datasets/Breast_Cancer.csv")

In [7]:
df.head(10)

,Age,Race,Marital Status,T Stage,N Stage,6th Stage,differentiate,Grade,A Stage,Tumor Size,Estrogen Status,Progesterone Status,Regional Node Examined,Reginol Node Positive,Survival Months,Status
0,68,White,Married,T1,N1,IIA,Poorly differentiated,3,Regional,4,Positive,Positive,24,1,60,Alive
1,50,White,Married,T2,N2,IIIA,Moderately differentiated,2,Regional,35,Positive,Positive,14,5,62,Alive
2,58,White,Divorced,T3,N3,IIIC,Moderately differentiated,2,Regional,63,Positive,Positive,14,7,75,Alive
3,58,White,Married,T1,N1,IIA,Poorly differentiated,3,Regional,18,Positive,Positive,2,1,84,Alive
4,47,White,Married,T2,N1,IIB,Poorly differentiated,3,Regional,41,Positive,Positive,3,1,50,Alive
5,51,White,Single,T1,N1,IIA,Moderately differentiated,2,Regional,20,Positive,Positive,18,2,89,Alive
6,51,White,Married,T1,N1,IIA,Well differentiated,1,Regional,8,Positive,Positive,11,1,54,Alive
7,40,White,Married,T2,N1,IIB,Moderately differentiated,2,Regional,30,Positive,Positive,9,1,14,Dead
8,40,White,Divorced,T4,N3,IIIC,Poorly differentiated,3,Regional,103,Positive,Positive,20,18,70,Alive
9,69,White,Married,T4,N3,IIIC,Well differentiated,1,Distant,32,Positive,Positive,21,12,92,Alive

In [5]:
df.columns

Index(['Age', 'Race', 'Marital Status', 'T Stage ', 'N Stage', '6th Stage',
       'differentiate', 'Grade', 'A Stage', 'Tumor Size', 'Estrogen Status',
       'Progesterone Status', 'Regional Node Examined',
       'Reginol Node Positive', 'Survival Months', 'Status'],
      dtype='object')

### Data Prepocessing

In [6]:
df.shape

(4024, 16)

In [8]:
df.isnull().sum()

Age                       0
Race                      0
Marital Status            0
T Stage                   0
N Stage                   0
6th Stage                 0
differentiate             0
Grade                     0
A Stage                   0
Tumor Size                0
Estrogen Status           0
Progesterone Status       0
Regional Node Examined    0
Reginol Node Positive     0
Survival Months           0
Status                    0
dtype: int64

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4024 entries, 0 to 4023
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Age                     4024 non-null   int64
 1   Race                    4024 non-null   object
 2   Marital Status          4024 non-null   object
 3   T Stage                 4024 non-null   object
 4   N Stage                 4024 non-null   object
 5   6th Stage               4024 non-null   object
 6   differentiate           4024 non-null   object
 7   Grade                   4024 non-null   object
 8   A Stage                 4024 non-null   object
 9   Tumor Size              4024 non-null   int64
 10  Estrogen Status         4024 non-null   object
 11  Progesterone Status     4024 non-null   object
 12  Regional Node Examined  4024 non-null   int64
 13  Reginol Node Positive   4024 non-null   int64
 14  Survival Months         4024 non-null   int64
 15  Status                  4024 non-null   object
dtypes: int64(5), object(11)
memory usage: 503.1+ KB

In [16]:


# Remove leading and trailing spaces from all column names
df.columns = df.columns.str.strip()

In [17]:
print(df.columns.tolist())

['Age', 'T Stage', 'N Stage', '6th Stage', 'differentiate', 'Grade', 'A Stage', 'Tumor Size', 'Regional Node Examined', 'Reginol Node Positive', 'Survival Months', 'Status', 'Race_Other', 'Race_White', 'Marital Status_Married', 'Marital Status_Separated', 'Marital Status_Single', 'Marital Status_Widowed', 'Estrogen Status_Positive', 'Progesterone Status_Positive']

In [18]:
nominal_cols = [
    "Race",
    "Marital Status",
    "Estrogen Status",
    "Progesterone Status"
]

In [19]:
ordinal_cols = [
    "T Stage",
    "N Stage",
    "6th Stage",
    "differentiate",
    "Grade",
    "A Stage"
]

In [20]:
df = pd.get_dummies(
    df,
    columns=nominal_cols,
    drop_first=True
)

KeyError: "None of [Index(['Race', 'Marital Status', 'Estrogen Status', 'Progesterone Status'], dtype='object')] are in the [columns]"

In [21]:
import pandas as pd

from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [14]:
encoder = OrdinalEncoder()

In [22]:
df[ordinal_cols] = encoder.fit_transform(df[ordinal_cols])

In [23]:
df["Status"] = df["Status"].map({
    "Alive": 1,
    "Dead": 0
})

In [24]:
df.head()

,Age,T Stage,N Stage,6th Stage,differentiate,Grade,A Stage,Tumor Size,Regional Node Examined,Reginol Node Positive,Survival Months,Status,Race_Other,Race_White,Marital Status_Married,Marital Status_Separated,Marital Status_Single,Marital Status_Widowed,Estrogen Status_Positive,Progesterone Status_Positive
0,68,0.0,0.0,0.0,1.0,3.0,1.0,4,24,1,60,1,False,True,True,False,False,False,True,True
1,50,1.0,1.0,2.0,0.0,2.0,1.0,35,14,5,62,1,False,True,True,False,False,False,True,True
2,58,2.0,2.0,4.0,0.0,2.0,1.0,63,14,7,75,1,False,True,False,False,False,False,True,True
3,58,0.0,0.0,0.0,1.0,3.0,1.0,18,2,1,84,1,False,True,True,False,False,False,True,True
4,47,1.0,0.0,1.0,1.0,3.0,1.0,41,3,1,50,1,False,True,True,False,False,False,True,True

### Splitind Dataset

In [25]:
X=df.drop('Status',axis=1)
y=df['Status']

In [27]:
print(X.shape)
print(y.shape)

(4024, 19)
(4024,)

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [30]:
from sklearn.preprocessing import StandardScaler

scalar=StandardScaler()

X_train=scalar.fit_transform(X_train)
X_test=scalar.transform(X_test)

### ANN Model Building

In [34]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Input

In [36]:
model=Sequential()

model.add(Input(shape=(X_train.shape[1],)))

# Hidden Layer 1
model.add(Dense(units=32, activation='relu'))

# Hidden Layer 2
model.add(Dense(units=16, activation='relu'))

# Hidden Layer 3
model.add(Dense(units=8, activation='relu'))

# Output Layer
model.add(Dense(units=1, activation='sigmoid'))

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (None, 32)             │           640 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,313 (5.13 KB)

 Trainable params: 1,313 (5.13 KB)

 Non-trainable params: 0 (0.00 B)

In [37]:
history = model.fit(
    X_train,
    y_train,
    epochs=50,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

Epoch 1/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - accuracy: 0.4703 - loss: 0.8146 - val_accuracy: 0.8447 - val_loss: 0.6195
Epoch 2/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8474 - loss: 0.5070 - val_accuracy: 0.8634 - val_loss: 0.4034
Epoch 3/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8687 - loss: 0.3518 - val_accuracy: 0.8758 - val_loss: 0.3515
Epoch 4/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8850 - loss: 0.3051 - val_accuracy: 0.8773 - val_loss: 0.3361
Epoch 5/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8928 - loss: 0.2874 - val_accuracy: 0.8711 - val_loss: 0.3313
Epoch 6/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8983 - loss: 0.2785 - val_accuracy: 0.8773 - val_loss: 0.3282
Epoch 7/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9010 - loss: 0.2716 - val_accuracy: 0.8789 - val_loss: 0.3247
Epoch 8/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9033 - loss: 0.2676 - val_accuracy: 0.8789 - val_loss: 0.3219
Epoch 9/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9025 - loss: 0.2643 - val_accuracy: 0.8742 - val_loss: 0.3228
Epoch 10/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9049 - loss: 0.2610 - val_accuracy: 0.8789 - val_loss: 0.3229
Epoch 11/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9068 - loss: 0.2592 - val_accuracy: 0.8789 - val_loss: 0.3200
Epoch 12/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9087 - loss: 0.2552 - val_accuracy: 0.8804 - val_loss: 0.3207
Epoch 13/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9072 - loss: 0.2534 - val_accuracy: 0.8804 - val_loss: 0.3209
Epoch 14/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9107 - loss: 0.2500 - val_accuracy: 0.8773 - val_loss: 0.3228
Epoch 15/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9107 - loss: 0.2481 - val_accuracy: 0.8758 - val_loss: 0.3220
Epoch 16/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9118 - loss: 0.2463 - val_accuracy: 0.8758 - val_loss: 0.3215
Epoch 17/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9118 - loss: 0.2443 - val_accuracy: 0.8789 - val_loss: 0.3233
Epoch 18/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9111 - loss: 0.2424 - val_accuracy: 0.8758 - val_loss: 0.3253
Epoch 19/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9161 - loss: 0.2398 - val_accuracy: 0.8804 - val_loss: 0.3253
Epoch 20/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9165 - loss: 0.2372 - val_accuracy: 0.8804 - val_loss: 0.3271
Epoch 21/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9146 - loss: 0.2360 - val_accuracy: 0.8773 - val_loss: 0.3278
Epoch 22/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9153 - loss: 0.2337 - val_accuracy: 0.8804 - val_loss: 0.3276
Epoch 23/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9161 - loss: 0.2325 - val_accuracy: 0.8820 - val_loss: 0.3300
Epoch 24/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9188 - loss: 0.2296 - val_accuracy: 0.8773 - val_loss: 0.3298
Epoch 25/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9169 - loss: 0.2283 - val_accuracy: 0.8742 - val_loss: 0.3350
Epoch 26/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9204 - loss: 0.2250 - val_accuracy: 0.8804 - val_loss: 0.3350
Epoch 27/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9184 - loss: 0.2247 - val_accuracy: 0.8758 - val_loss: 0.3378
Epoch 28/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9227 - loss: 0.2221 - val_accuracy: 0.8773 - val_loss: 0.3418
Epoch 29/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9212 - loss: 0.2210 - val_accuracy: 0.8758 - val_loss: 0.3424
Epoch 30/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9231 - loss: 0.2184 - val_accuracy: 0.8727 - val_loss: 0.3485
Epoch 31/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9231 - loss: 0.2167 - val_accuracy: 0.8711 - val_loss: 0.3446
Epoch 32/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9216 - loss: 0.2148 - val_accuracy: 0.8665 - val_loss: 0.3476
Epoch 33/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9243 - loss: 0.2130 - val_accuracy: 0.8758 - val_loss: 0.3491
Epoch 34/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9235 - loss: 0.2113 - val_accuracy: 0.8696 - val_loss: 0.3548
Epoch 35/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9266 - loss: 0.2085 - val_accuracy: 0.8680 - val_loss: 0.3560
Epoch 36/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9285 - loss: 0.2076 - val_accuracy: 0.8680 - val_loss: 0.3609
Epoch 37/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9282 - loss: 0.2048 - val_accuracy: 0.8696 - val_loss: 0.3622
Epoch 38/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9289 - loss: 0.2031 - val_accuracy: 0.8696 - val_loss: 0.3798
Epoch 39/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9274 - loss: 0.2027 - val_accuracy: 0.8680 - val_loss: 0.3639
Epoch 40/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9313 - loss: 0.2003 - val_accuracy: 0.8680 - val_loss: 0.3662
Epoch 41/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9320 - loss: 0.1999 - val_accuracy: 0.8649 - val_loss: 0.3807
Epoch 42/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9297 - loss: 0.1969 - val_accuracy: 0.8665 - val_loss: 0.3761
Epoch 43/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9305 - loss: 0.1954 - val_accuracy: 0.8634 - val_loss: 0.3798
Epoch 44/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9336 - loss: 0.1923 - val_accuracy: 0.8711 - val_loss: 0.3866
Epoch 45/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9313 - loss: 0.1926 - val_accuracy: 0.8680 - val_loss: 0.3842
Epoch 46/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9344 - loss: 0.1883 - val_accuracy: 0.8696 - val_loss: 0.3811
Epoch 47/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9344 - loss: 0.1893 - val_accuracy: 0.8649 - val_loss: 0.3860
Epoch 48/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9348 - loss: 0.1869 - val_accuracy: 0.8634 - val_loss: 0.3895
Epoch 49/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9348 - loss: 0.1854 - val_accuracy: 0.8680 - val_loss: 0.3886
Epoch 50/50
81/81 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9355 - loss: 0.1857 - val_accuracy: 0.8680 - val_loss: 0.3916

In [39]:
history.history.keys()

dict_keys(['accuracy', 'loss', 'val_accuracy', 'val_loss'])

In [40]:
test_loss, test_accuracy = model.evaluate(X_test, y_test)

print("Test Loss:", test_loss)
print("Test Accuracy:", test_accuracy)

26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8919 - loss: 0.3292
Test Loss: 0.3291529715061188
Test Accuracy: 0.8919254541397095

In [41]:
predictions = model.predict(X_test)

26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step

In [42]:
y_pred = (predictions > 0.5).astype(int)

In [46]:
error_count=0

for i in range(50):
    print(f"Actual: {y_test.iloc[i]}  Predicted: {y_pred[i][0]}")
    if(y_test.iloc[i]!=y_pred[i][0]):
        error_count+=1

print("The Error count is:",error_count)

Actual: 1  Predicted: 1
Actual: 1  Predicted: 1
Actual: 1  Predicted: 1
Actual: 0  Predicted: 1
Actual: 1  Predicted: 1
Actual: 1  Predicted: 1
Actual: 1  Predicted: 1
Actual: 1  Predicted: 1
Actual: 0  Predicted: 0
Actual: 1  Predicted: 1
Actual: 1  Predicted: 1
Actual: 1  Predicted: 1
Actual: 1  Predicted: 1
Actual: 1  Predicted: 1
Actual: 0  Predicted: 1
Actual: 1  Predicted: 1
Actual: 1  Predicted: 1
Actual: 1  Predicted: 1
Actual: 1  Predicted: 1
Actual: 1  Predicted: 1
Actual: 1  Predicted: 1
Actual: 1  Predicted: 1
Actual: 0  Predicted: 0
Actual: 0  Predicted: 1
Actual: 1  Predicted: 1
Actual: 1  Predicted: 1
Actual: 1  Predicted: 1
Actual: 1  Predicted: 1
Actual: 1  Predicted: 1
Actual: 1  Predicted: 1
Actual: 1  Predicted: 1
Actual: 1  Predicted: 1
Actual: 1  Predicted: 1
Actual: 1  Predicted: 1
Actual: 1  Predicted: 1
Actual: 1  Predicted: 1
Actual: 1  Predicted: 1
Actual: 0  Predicted: 0
Actual: 0  Predicted: 1
Actual: 0  Predicted: 0
Actual: 1  Predicted: 1
Actual: 1  Predicted: 1
Actual: 0  Predicted: 0
Actual: 1  Predicted: 1
Actual: 0  Predicted: 0
Actual: 1  Predicted: 1
Actual: 1  Predicted: 1
Actual: 1  Predicted: 1
Actual: 1  Predicted: 1
Actual: 0  Predicted: 1
The Error count is: 5